remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
“title: Welcome to the Shahrukh's homepage!”
description: Feel free to browse my projects!
